name: MEV-Share Bot

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  run-mev-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - name: Run Backrun Example
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          node dist/examples/sendBackrunBundle.js
